apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dynamic-template-git-file
spec:
  generators:
    - git:
        repoURL: https://github.com/vavdoshka/applicationset.git
        revision: testing-templating
        files:
        - path: "examples/untyped-template/git-file/apps/*.yaml"
  fullyUntypedTemplate: |
    metadata:
      name: '{{ .cluster }}-git-file-guestbook' # decide how to structure this, with guestbook or how
      annotations:
      {{ range $key, $val := . }}
        {{ if (hasPrefix "appAnnotations." $key ) }}
        {{ $key | replace "appAnnotations." "" }}: {{ $val }}
        {{ end }}
      {{ end }}
    spec:

      # USECASE - DEFAULT VALUE
      project: {{ default "default" .project }}

      source:
        repoURL: https://github.com/vavdoshka/applicationset.git
        targetRevision: HEAD
        path: examples/untyped-template/git-file/apps

        # USECASE - NON_PRIMITIVE TEMPLATING (https://github.com/argoproj/applicationset/issues/168#issue-840093112)
        {{ toYaml (fromJson .plugin) | nindent 4 }} 

        
      destination:
        server: '{{ .url }}'

        # USECASE - TEXT FORMATTING issues #447,#351,#518
        namespace: {{ trunc 63 (.namespace | replace "/" "-" | lower) }}

      # USECASE - CONTROLLING SYNC POLICY CREATION
      {{ if (eq .autosyncEnabled "true") }}
      syncPolicy:
        automated:
          # USECASE - NON-STRING PRIMITIVE TEMPLATING
          selfHeal: {{ eq .autosyncSelfHeal "true" }}
      {{ end }}
